spring.application.name=faster-whisper2

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.port=8080

app.transcription.chunk.max-mb=20
app.transcription.chunk.audio-bitrate-kbps=64
app.transcription.chunk.size-safety-factor=0.90
